### ISSUE TITLE
JSON2APEX help

### ISSUE THREAD

**Issue by Ramiya04** [superfell/json2apex#13]
Hi,
I am new to salesforce and have to create apex class for json string where  "profile" handles both string value and list of string value. I'm getting this error message when I save the code after I've converted into class using  http://json2apex.herokuapp.com/ .

Type cannot be constructed: String at "tags.add(new String(parser));"   could you please help to fix this and also handle string and list of string  value for profile class.  

Thanks

{
  "name" : {
    "givenName" : "smith",
    "familyName" : "peter",
    "formatted" : "Smith Peter"
  },
  "location" : "london",
  "type" : "person",
  "displayName" : "smith peter",
  "status" : "xyz gets recognized by industry analyst as a leader...",
  "tags" : [ "leadership", "financial", "analysis", "capital", "formation", "contract", "talent", "management", "entrepreneur" ],
  "published" : "2011-11-01T20:17:08.667+0000",
  "followingCount" : 64,
  "thumbnailUrl" : "https://xyz.com",
  "jive" : {
    "level" : {
      "name" : "Contributor",
      "description" : "",
      "points" : 65
    },
    "timeZone" : "America/New_York",
    "locale" : "en_US",
    "username" : "psmith",
    "profile" : [ {
      "value" : "President & CEO",
      "jive_label" : "Title"
    }, {
      "value" : "11/06/2011",
      "jive_label" : "Join Date"
    }, {
      "value" : "lived in NY ",
      "jive_label" : "Biography"
    }, {
      "value" : "",
      "jive_label" : "Expertise"
    }, {
      "value" : [ "Financial Services ", "Business Services " ],
      "jive_label" : "Industries"
    }, {
      "value" : [ "Finance ", "Business Development ", "Consulting ", "Business Analysis ", "Marketing " ],
      "jive_label" : "Disciplines"
    }, {
      "value" : ".",
      "jive_label" : "What do you do?"
    }, {
      "value" : "team.",
      "jive_label" : "My Style"
    }, {
      "value" : "http://www.xyz.com",
      "jive_label" : "Website"
    }, {
      "value" : "",
      "jive_label" : "Business Manager"
    }, {
      "value" : "http://www.facebook.com/x",
      "jive_label" : "Facebook"
    }, {
      "value" : "http://www.linkedin.com/in/x",
      "jive_label" : "LinkedIn"
    }, {
      "value" : "https://twitter.com/#!/x",
      "jive_label" : "Twitter"
    } ],
    "external" : false,
    "visible" : true,
    "enabled" : true,
    "externalContributor" : false,
    "federated" : false
  },
  "updated" : "2013-11-12T04:57:20.140+0000",
  "emails" : [ {
    "value" : "xyz.com@localhost",
    "type" : "work",
    "jive_label" : "Email",
    "primary" : true
  } ],
  "photos" : [ {
    "value" : "https://xy.com"
  } ],
  "thumbnailId" : "1093",
  "followerCount" : 50,
  "resources" : {
    "following" : {
      "ref" : "xy.xom",
      "allowed" : [ "GET" ]
    },
    "followers" : {
      "ref" : "xy.com",
      "allowed" : [ "GET" ]
    },

```
"activity" : {
  "ref" : "https://xys.com",
  "allowed" : [ "GET" ]
}
```

  },
  "id" : "2010"
}

**Comment by superfell** [comment]
fixed in todays changes
