### ISSUE TITLE
JSON element named 'protected' causes unexpected token: 'protected' in generated code

### ISSUE THREAD

**Issue by adtennant** [superfell/json2apex#14]
I've just used JSON2Apex to generate a class for the [Twitter statuses/update_with_media](https://dev.twitter.com/docs/api/1.1/post/statuses/update_with_media) response.

Unfortunately one of the JSON elements is named 'protected' which generates the following line in my class:

    public Boolean protected {get;set;}

Which causes the following compile error:

> unexpected token: 'protected'

I would assume this goes for other Apex keywords too.

**Comment by superfell** [comment]
fixed in d256e7420491801dd26e55e3e5749bf491b5d9a6
