### ISSUE TITLE
Error Code Help!

### ISSUE THREAD

**Issue by ericmontepanda** [superfell/json2apex#18]
superfell, I love using your json2apex and i've been using this in the last year to parse some intensive JSON file. Usually I don't have any problem with this, but today I'm hitting  a lot of issues that I'm unable to troubleshoot.

I've conducted some work investigating in my end, and looks like im hitting some errors within these lines:
---
"consumer": {
            "groups": [
                1,
                1392404368820,
                1392404368819
            ],
            "users": []
        }

---
Any feedback or help on this would be great!

Full JSON File Below

{
    "responseStatus": "SUCCESS",
    "doc": {
        "id": 710,
        "binder": false,
        "coordinator": {
            "groups": [],
            "users": []
        },
        "owner": {
            "groups": [],
            "users": [
                261997
            ]
        },
        "approver": {
            "groups": [],
            "users": [
                376516,
                261995
            ]
        },
        "reviewer": {
            "groups": [],
            "users": []
        },
        "distribution_contacts": {
            "groups": [],
            "users": []
        },
        "viewer": {
            "groups": [],
            "users": []
        },
        "consumer": {
            "groups": [
                1,
                1392404368820,
                1392404368819
            ],
            "users": []
        },
        "editor": {
            "groups": [],
            "users": [
                261995
            ]
        },
        "format": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "version_creation_date": "2015-10-27T18:50:49.640Z",
        "major_version_number": 2,
        "annotations_links": 0,
        "annotations_all": 0,
        "status": "Effective",
        "filename": "Veeva Standard Test1.docx",
        "version_created_by": 261995,
        "country": [
            "global"
        ],
        "annotations_anchors": 0,
        "document_number": "STD-0119",
        "minor_version_number": 0,
        "lifecycle": "Draft to Effective Lifecycle (PDF Only)",
        "crosslink": false,
        "annotations_notes": 0,
        "name": "Veeva Standard Test",
        "locked": false,
        "pages": 5,
        "type": "Standard",
        "description": "",
        "title": "Standard Test",
        "owning_department": [
            "00D000000000201"
        ],
        "size": 65247,
        "md5checksum": "number",
        "annotations_unresolved": 0,
        "last_modified_by": 1,
        "document_creation_date": "2015-10-27T18:47:30.603Z",
        "annotations_resolved": 0,
        "annotations_lines": 0,
        "version_modified_date": "2015-10-27T22:22:06.000Z",
        "created_by": 261997,
        "disable_vault_overlays": "false",
        "released_date": "2015-10-27",
        "topic_new": [
            "Reimbursements to Authors"
        ],
        "record_series_code": [
            "ICO160"
        ],
        "training_impact": "true",
        "effective_date": "2015-10-27",
        "approval_target_date": "2015-12-15",
        "next_periodic_review_date": "2018-09-26",
        "psmf": "true",
        "area_new": [
            "Medical"
        ],
        "planned_release_date": "2015-11-16",
        "quality_system_name": [
            "SEQS"
        ],
        "process_new": [
            "Create & Disclose MSI"
        ],
        "approved_date": "2015-10-27",
        "course_id": "BET # 12345"
    },

    "renditions": {
        "viewable_rendition": "URL"
    },
    "versions": [
        {
            "vnumber": "2.0",
            "value": "URL"
        }
    ]
}

**Comment by superfell** [comment]
Here's the exception

RuntimeException occured : Can't add an class java.lang.Long to a collection of class models.ApexPrimative

play.exceptions.JavaExecutionException: Can't add an class java.lang.Long to a collection of class models.ApexPrimative
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: Can't add an class java.lang.Long to a collection of class models.ApexPrimative
	at models.TypeFactory.typeOfCollection(TypeFactory.java:98)
	at models.TypeFactory.typeOfObject(TypeFactory.java:62)
	at models.TypeFactory.makeMembers(TypeFactory.java:127)
	at models.TypeFactory.typeOfMap(TypeFactory.java:107)
	at models.TypeFactory.typeOfObject(TypeFactory.java:64)
	at models.TypeFactory.makeMembers(TypeFactory.java:127)
	at models.TypeFactory.typeOfMap(TypeFactory.java:107)
	at models.TypeFactory.typeOfObject(TypeFactory.java:64)
	at models.TypeFactory.makeMembers(TypeFactory.java:127)
	at models.TypeFactory.typeOfMap(TypeFactory.java:107)
	at models.TypeFactory.typeOfObject(TypeFactory.java:64)
	at controllers.Application.makeApex(Application.java:45)

**Comment by superfell** [comment]
And here's a minimal repo case
{"consumer": [1, 1392404368819 ] }

Guessing this is related to java types, 1 will be an int and the other number is probably a long, and the code that works out the array types doesn't handle promoting the int to a long.

**Comment by ericmontepanda** [comment]
Hey thanks for looking into this!!! Now I know what to look for next time, and I made changes to the json to make it a string file so I don't receive the error. 

Thanks again
