### ISSUE TITLE
Missing key word: date

### ISSUE THREAD

**Issue by nzidol** [superfell/json2apex#19]
And when I generate the parse code it comes up with an error?? Probably can't pass a parser to Object?

![capture](https://cloud.githubusercontent.com/assets/13618973/11053912/4de5bbd2-87ca-11e5-9168-f0994fcd8625.PNG)

Cheers,

**Comment by nzidol** [comment]
ok understand it now, the JSON says:
           "portalId": null,
Probably better to parse that as an empty string?

**Comment by superfell** [comment]
Fixed.
