### ISSUE TITLE
Problems parsing objects beginning with underscores

### ISSUE THREAD

**Issue by amazingjoe** [superfell/json2apex#20]
I have an API response that looks like this:

`{
  "_total": 2,
  "event_template": {
    "_count": 2,
    "_data": [
      {
        "capacity": 200,
        "dedicated_order": false,
        "description": "Time to celebrate! Join us on the evening of the 24th December.",
        "event_type": "single",
        "fee_set_id": null,
        "hidden_type": "public_browsable",
        "id": "98214576-4326-78d7-2938-05e1e73986b5",
        "name": "Christmas Eve Party",
        "oversell_capacity": 10,
        "portal_id": "3e250611-fc58-4821-a0d2-82df7daf4d1e",
        "private_event_code": null,
        "release_sessions_until": null,
        "seller_id": "dbd5e1a7-f0cb-afad-bdf3-c5d692ee4355",
        "ticket_template_id": null,
        "venue_id": "bd94ed49-dadf-48b3-f47f-abe4df185289"
      },
      {
        "capacity": 500,
        "dedicated_order": false,
        "description": "Break out those dancing shoes! We host live music and dancing every friday night from 5pm!",
        "event_type": "repeating",
        "fee_set_id": null,
        "hidden_type": "public_browsable",
        "id": "f5ef3d01-b80b-c915-bc8b-9d7d48fc2d43",
        "name": "Friday Night Dancing",
        "oversell_capacity": 10,
        "portal_id": "3e250611-fc58-4821-a0d2-82df7daf4d1e",
        "private_event_code": null,
        "release_sessions_until": "2016-12-21T07:59:59Z",
        "seller_id": "dbd5e1a7-f0cb-afad-bdf3-c5d692ee4355",
        "ticket_template_id": null,
        "venue_id": "bd94ed49-dadf-48b3-f47f-abe4df185289"
      }
    ],
    "_total": 2
  },
  "venue": {
    "_count": 1,
    "_data": [
      {
        "address": "123 Somewhere St\nAnywhereville, CA\nUnited States",
        "country": "US",
        "description": "A venue that'll last the tide.",
        "email": "info@sandbox.stqrytix.com",
        "id": "bd94ed49-dadf-48b3-f47f-abe4df185289",
        "name": "Sandbox Event Center",
        "phone": "+1 (123) 555-5555",
        "portal_id": "3e250611-fc58-4821-a0d2-82df7daf4d1e",
        "timezone": "America/Los_Angeles",
        "website": "sandbox.stqrytix.com"
      }
    ],
    "_total": 1
  }
}`

The generator produces code that is causing an error (using the Create explicit parse code option). In this case line 20:

`public class _data {`

produces the following error:
no viable alternative at character '_' (Line: 20, Column: 14)

My thought is that the class name must begin with a letter to be valid?

When I append a letter in front of the underscore it seems to let me save without an error.

**Comment by superfell** [comment]
Fixed with today's changes.
