### ISSUE TITLE
Type name already in use: JSON2Apex.JSON2Apex

### ISSUE THREAD

**Issue by madhu-ra** [superfell/json2apex#23]
Generated Apex class is having a nested class with same name and causing compile issue as in the title

**Comment by superfell** [comment]
please provide details of how to reproduce this

**Comment by all2human** [comment]
//
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class PaymentMethods {

	public class CreditCards {
		public String id;
		public Boolean defaultPaymentMethod;
		public String cardType;
		public String cardNumber;
		public Integer expirationMonth;
		public Integer expirationYear;
		public CardHolderInfo cardHolderInfo;
	}

	public class CardHolderInfo {
		public String cardHolderName;
		public String addressLine1;
		public Object addressLine2;
		public String city;
		public String state;
		public String zipCode;
		public String country;
		public Object phone;
		public Object email;
	}

	public class PaymentMethods {
		public List<CreditCards> creditCards;
		public Boolean success;
	}

	
	public static PaymentMethods parse(String json) {
		return (PaymentMethods) System.JSON.deserialize(json, PaymentMethods.class);
	}
}

**Comment by madhu-ra** [comment]
Below is the raw JSON I used to produce the stub. I verified this as a valid JSON by parsing to a json viewr. When I tried to create the generated class in my org I'm receiving above mentioned error message.

`{"transaction":{"id":"11e787c69b1f005ebb5ac08f","payment_method":"cc","account_vault_id":null,"recurring_id":null,"first_six":"411111","last_four":"1111","account_holder_name":null,"transaction_amount":"50.00","description":null,"transaction_code":null,"avs":null,"batch":"1","order_num":"766217846000","verbiage":"APPROVAL","transaction_settlement_status":null,"effective_date":null,"routing":null,"return_date":null,"created_ts":1503467273,"modified_ts":1503467273,"transaction_api_id":null,"terms_agree":null,"notification_email_address":null,"notification_email_sent":true,"response_message":null,"auth_amount":"50.00","auth_code":"87c69b","status_id":101,"type_id":20,"location_id":"11e77b6f5730545a87cc3702","reason_code_id":1000,"contact_id":null,"billing_zip":null,"billing_street":null,"product_transaction_id":"11e77b6f58219c8eb935a9c2","tax":0,"customer_ip":null,"customer_id":null,"po_number":null,"avs_enhanced":"V","cvv_response":"N","billing_phone":null,"billing_city":null,"billing_state":null,"clerk_number":null,"tip_amount":"0.00","created_user_id":"11e76e458be8fe4aaf3ff8b1","modified_user_id":"11e76e458be8fe4aaf3ff8b1","settle_date":null,"charge_back_date":null,"void_date":null,"account_type":"visa","is_recurring":false,"is_accountvault":false,"transaction_c1":null,"transaction_c2":null,"transaction_c3":null,"additional_amounts":[],"terminal_serial_number":null,"entry_mode_id":"K","terminal_id":null,"checkin_date":"2017-08-10","checkout_date":"2017-08-10","room_num":null,"room_rate":"5.00","advance_deposit":false,"no_show":false,"emv_receipt_data":null,"_links":{"self":{"href":"https://apiv2.sandbox.zeamster.com/v2/transactions/11e787c69b1f005ebb5ac08f"}}}}`

**Comment by akcorp2003** [comment]
I'm seeing a similar issue with my JSON:

```

{
  "requestor_info": {
    "interface_relationship_id": "string"
  },
  "customer_details": {
    "classification_code": 1001,
    "format_code": "string",
    "value": "string"
  },
  "supporting_data_group": {
    "country_code": "string",
    "region": "string",
    "entity": "string"
  },
  "request_group": [
    {
      "preference_code": "string"
    }
  ],
  "audit_info": {
    "correlation_id": "string"
  }
}
```

It seems that an inner class with the same name is being created.

**Comment by BobHatcher** [comment]
I also had this problem. To address it I took the outer class and appended its name with `Wrapper`.

Then, to parse my JSON,
`MyJSONClassWrapper.MyJSONClass myResponse = MyJSONClassWrapper.parse(response);`

I also then had to make comparable adjustments in the test class.

**Comment by bobbywhitesfdc** [comment]
I've just seen the same issue.  My JSON is similar:
https://th-superbadge-apex.herokuapp.com/equipment

[{"_id":"55d66226726b611100aaf741","replacement":false,"quantity":5,"name":"Generator 1000 kW","maintenanceperiod":365,"lifespan":120,"cost":5000,"sku":"100003"},{"_id":"55d66226726b611100aaf742","replacement":true,"quantity":183,"name":"Cooling Fan","maintenanceperiod":0,"lifespan":0,"cost":300,"sku":"100004"},{"_id":"55d66226726b611100aaf743","replacement":true,"quantity":143,"name":"Fuse 20A","maintenanceperiod":0,"lifespan":0,"cost":22,"sku":"100005"},{"_id":"55d66226726b611100aaf744","replacement":false,"quantity":5,"name":"Generator 2000 kw","maintenanceperiod":365,"lifespan":120,"cost":6000,"sku":"100006"},{"_id":"55d66226726b611100aaf745","replacement":true,"quantity":142,"name":"Fuse 25A","maintenanceperiod":0,"lifespan":0,"cost":28,"sku":"100007"},{"_id":"55d66226726b611100aaf746","replacement":true,"quantity":122,"name":"Fuse 13A","maintenanceperiod":0,"lifespan":0,"cost":10,"sku":"100008"},{"_id":"55d66226726b611100aaf747","replacement":true,"quantity":90,"name":"Ball Valve 10 cm","maintenanceperiod":0,"lifespan":0,"cost":50,"sku":"100009"},{"_id":"55d66226726b611100aaf748","replacement":false,"quantity":2,"name":"Converter","maintenanceperiod":180,"lifespan":120,"cost":3000,"sku":"100010"},{"_id":"55d66226726b611100aaf749","replacement":true,"quantity":75,"name":"Ball Valve 8 cm","maintenanceperiod":0,"lifespan":0,"cost":42,"sku":"100011"},{"_id":"55d66226726b611100aaf74a","replacement":true,"quantity":100,"name":"Breaker 25A","maintenanceperiod":0,"lifespan":0,"cost":30,"sku":"100012"},{"_id":"55d66226726b611100aaf74b","replacement":true,"quantity":150,"name":"Switch","maintenanceperiod":0,"lifespan":0,"cost":100,"sku":"100013"},{"_id":"55d66226726b611100aaf74c","replacement":true,"quantity":200,"name":"Ball Valve 5 cm","maintenanceperiod":0,"lifespan":0,"cost":30,"sku":"100014"},{"_id":"55d66226726b611100aaf74d","replacement":false,"quantity":8,"name":"UPS 3000 VA","maintenanceperiod":180,"lifespan":60,"cost":1600,"sku":"100015"},{"_id":"55d66226726b611100aaf74e","replacement":false,"quantity":10,"name":"UPS 1000 VA","maintenanceperiod":180,"lifespan":48,"cost":1000,"sku":"100016"},{"_id":"55d66226726b611100aaf74f","replacement":true,"quantity":180,"name":"Breaker 8A","maintenanceperiod":0,"lifespan":0,"cost":10,"sku":"100017"},{"_id":"55d66226726b611100aaf750","replacement":false,"quantity":2,"name":"Cooling Tower","maintenanceperiod":365,"lifespan":120,"cost":10000,"sku":"100018"},{"_id":"55d66226726b611100aaf751","replacement":true,"quantity":165,"name":"Motor","maintenanceperiod":0,"lifespan":0,"cost":150,"sku":"100019"},{"_id":"55d66226726b611100aaf752","replacement":true,"quantity":210,"name":"Breaker 13A","maintenanceperiod":0,"lifespan":0,"cost":20,"sku":"100020"},{"_id":"55d66226726b611100aaf753","replacement":true,"quantity":100,"name":"Radiator Pump","maintenanceperiod":0,"lifespan":0,"cost":500,"sku":"100021"},{"_id":"55d66226726b611100aaf754","replacement":true,"quantity":129,"name":"Breaker 20A","maintenanceperiod":0,"lifespan":0,"cost":25,"sku":"100022"},{"_id":"55d66226726b611100aaf73f","replacement":false,"quantity":10,"name":"UPS 2000 VA","maintenanceperiod":180,"lifespan":60,"cost":1350,"sku":"100001"},{"_id":"55d66226726b611100aaf740","replacement":true,"quantity":194,"name":"Fuse 8A","maintenanceperiod":0,"lifespan":0,"cost":5,"sku":"100002"}]

The "record" that's internal is unnamed.  The generated code creates an inner class with the same name as the outer.

//
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class PartsServiceWrapper {

	public class PartsServiceWrapper {
		public String _id;
		public Boolean replacement;
		public Integer quantity;
		public String name;
		public Integer maintenanceperiod;
		public Integer lifespan;
		public Integer cost;
		public String sku;
	}

	
	public static List<PartsServiceWrapper> parse(String json) {
		return (List<PartsServiceWrapper>) System.JSON.deserialize(json, List<PartsServiceWrapper>.class);
	}
}

**Comment by superfell** [comment]
Fixed with latest changes.
