### ISSUE TITLE
Under class same name has JSON field

### ISSUE THREAD

**Issue by Wykett** [superfell/json2apex#30]
Hi,
Not 100% sure, but my JSON was the following:
### JSON
{"Field_name":{"other_field":"value"}}

### Code created
The code you created was:
//
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class JSON2Apex {
	public Field_name Field_name;
	class Field_name {
		public String other_field;
	}
	public static JSON2Apex parse(String json) {
		return (JSON2Apex) System.JSON.deserialize(json, JSON2Apex.class);
	}
}

### Problem
However, other_field has null has value.

### Solution
What I noticed is that if I changed the class name Field_name to TmpField_name, it is working.
So my final result is:
//
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class JSON2Apex {
	public TmpField_name Field_name;
	class TmpField_name {
		public String other_field;
	}
	public static JSON2Apex parse(String json) {
		return (JSON2Apex) System.JSON.deserialize(json, JSON2Apex.class);
	}
}

Is it normal?

**Comment by superfell** [comment]
You're allowed to have a filename with the same name as a class name, the original code works fine.
