### ISSUE TITLE
JSON keys with DASH/Hyphen is not supported. 

### ISSUE THREAD

**Issue by yasarshaikh** [superfell/json2apex#34]
```json
{ 
   "customer-id" : "1123"
}
```

These types of JSON is not having proper class. Even the class has variables like 
`public String customer-id{get;set;}`

which is not valid in Apex.

**Comment by josephbleau** [comment]
Simple and obvious fix is to replace hyphens with underscores. This will mean that elements "foo-bar" and "foo_bar" if both present in a single JSON would collide and one would end up with an affix, but I think that's acceptable. There are probably other such replacements that could be made, but for now I've made a quick PR with this simple change.

**Comment by josephbleau** [comment]
https://github.com/superfell/json2apex/pull/35

**Comment by superfell** [comment]
Fixed in 9dc0e18d50faee7f85371ae0305d8517ba8220ef thanks @josephbleau 
And is now deployed.
