### ISSUE TITLE
Guide me to Run this on Local PC

### ISSUE THREAD

**Issue by kairavi-baxi** [superfell/json2apex#39]
Hi. Can anyone help me to run this code on my local pc?
What steps should I follow?

**Comment by superfell** [comment]
1. install play 1.x see https://www.playframework.com/releases
2. checkout this repo, git clone https://github.com/superfell/json2apex.git
3. from the repo dir, run `play run'
4. open a browser to http://localhost:9091

**Comment by kairavi-baxi** [comment]
Thank you so much still i am facing some issue. can you help me with teamviewer?

**Comment by kairavi-baxi** [comment]
![compile-error](https://user-images.githubusercontent.com/71176565/105393467-62cb0000-5c42-11eb-8cf8-1096d0fe3fd0.PNG)
please see this.need help

**Comment by kairavi-baxi** [comment]
can you guide me how to run it with Eclipse IDE ? @superfell @metadaddy Please Help.

**Comment by superfell** [comment]
see https://www.playframework.com/documentation/1.5.x/ide
